baseURL = "https://P-seudonymous.github.io/"
languageCode = "en-us"
title = "Aryan Saraf"
theme = "PaperMod"

[params]
  description = "Hardware Security, Applied Cryptography, SCA/FIA, Secure Firmware"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.profileMode]
enabled = true

title = "Aryan Saraf"

subtitle = """
Cyber Physical Systems Undergrad @ MIT, Manipal

Hardware Security
Applied Cryptography
Side-Channel Analysis
Capture The Flag

Current Position

Summer Research Intern
IIT Bombay
"""

imageUrl = "/pfp.png"

imageTitle = "Aryan Saraf"


[[params.profileMode.buttons]]
name = "Resume"
url = "/resume"

[[params.profileMode.buttons]]
name = "Research"
url = "/research"

[[params.profileMode.buttons]]
name = "Writeups"
url = "/writeups"

[[params.socialIcons]]
name = "x"
url = "https://x.com/__pseudonymous_"

[[params.socialIcons]]
name = "github"
url = "https://github.com/P-seudonymous"

[[params.socialIcons]]
name = "email"
url = "mailto:aryan.sarafhp@gmail.com"
